version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pip3 install -r requirements.txt --user
      - run:
          command: python tests/test_first.py
