version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: pip3 install -r requirements.txt --user
      - run:
          command: python tests/test_first.py "Mi-9-sdk28" 192.168.1.207:7401
      - store_artifacts:
          path: results
